name 'capstone_cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures capstone_cookbook'
long_description 'Installs/Configures capstone_cookbook'
version '0.1.0'

depends 'application', '~> 5.0'
depends 'application_git', '~> 1.0'
depends 'application_javascript', '~> 1.0'
depends 'build-essential'
depends 'poise', '~> 2.0'